
services:
  mysql:
    image: mysql:8.0
    container_name: algafood-mysql
    environment:
      MYSQL_DATABASE: algafood
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
